[default]
src = 'src'
test = 'test'
out = 'out'
libs = ['lib']
solc_version = '0.8.13'
optimizer = true
optimizer_runs = 10000

gas_reports = ["*"]

# See more config options https://github.com/gakonst/foundry/tree/master/config
