remote_theme: just-the-docs/just-the-docs

# Aux links for the upper right navigation
aux_links:
  "visit HAECHI LABS":
    - "//haechi.io/en"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
